# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ccdda8c7f07397032b33f8024dd1bd4746848ce093f8ffaeeb1c57c153fd7ecd1d9bc1df7d6447bbd2400b2796146c6f29d4cd3e73e0647f147e8ab6e6d28e2

test:
  secret_key_base: 5a54344e44ef67f12b431a0f0d2bf9b9e89d640af3daa3dceade51460fb269b2860f5fb2ac53b21fa04f05762bb5cb6cd2516b7eaf3a47aef0b0ed118a51b690

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
